# name of disease/trait. used as prefix for output files.
study: skin_disease

gwas_catalog: assets/gwas_catalog_v1.0-associations_e100_r2021-04-20.tsv

disease_list: skin_disease_list.tsv

extra_gwas: skin_disease_SNPS_other_papers.txt

gwas_pvalue_threshold: 5e-8

retry_errors: false

seed: 1234

epigenome_csv: epigenome.csv

# epigenome:
#   - ATAC:
#       bedfile: data/ggr.atac.idr.master.bed.gz
#       genome: hg19
#       filter: true
#   - H3K27ac:
#       bedfile: data/ggr.histone.H3K27ac.overlap.master.bed.gz
#       genome: hg19
#       filter: true
#   - H3K27me3:
#       bedfile: data/ggr.histone.H3K27me3.overlap.master.bed.gz
#       genome: hg19
#       filter: false
#   - H3K4me1:
#       bedfile: data/ggr.histone.H3K4me1.overlap.master.bed.gz
#       genome: hg19
#       filter: true


# uncomment to filter out
txdb_filters:
 - coding
#  - spliceSite
#  - fiveUTR
#  - threeUTR
#  - intron
#  - promoter
#  - intergenic

eqtls:
  - skin_not_sun_exposed:
      file: data/Skin_Not_Sun_Exposed_Suprapubic.v8.signif_variant_gene_pairs.txt.gz
      filter: false
  - skin_sun_exposed:
      file: data/Skin_Sun_Exposed_Lower_leg.v8.signif_variant_gene_pairs.txt.gz
      filter: false


barcodes: assets/barcodes16-1.txt

random_controls: 250

oligo:
  max_len: 230
  primer_5p: ACTGGCCGCTTCACTG
  primer_3p: AGATCGGAAGAGCGTCG
  # cloning_site: CTCGAGGCTAGC
  bc_len: 16
  max_indel: 3

restriction_enzymes:
  EcoRI: GAATTC
  BamHI: GGATCC
  XhoI: CTCGAG
  NheI: GCTAGC

cloning_site:
  enzyme1: XhoI
  enzyme2: NheI
  stuffer_bp: 10
  stuffer_GC: 0.5

